version: '2.0'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  app:
    container_name: ikea-product-module
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - mongo